name: FlagIds

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  verify-flagids:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Verify flag mappings
        run: node ./scripts/verify-flagids.mjs
